name: Build Flutter Android APK (Debug)

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android components
        run: |
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0" "ndk;27.1.12297006"
          yes | sdkmanager --licenses

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      - name: Write local.properties
        run: echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties

      - name: Write local.properties
        run: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
          echo "flutter.versionCode=1" >> android/local.properties
          echo "flutter.versionName=1.0" >> android/local.properties

      - name: Pub get
        run: flutter pub get

      - name: Pin NDK & Gradle opts
        run: |
          echo "android.ndkVersion=27.1.12297006" >> android/gradle.properties
          echo "org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=512m" >> android/gradle.properties
          echo "org.gradle.daemon=true" >> android/gradle.properties

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ble_bridge-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
