name: Build Flutter Android APK (Debug)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android components
        run: |
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0" "platforms;android-33" "cmake;3.22.1" "ndk;27.1.12297006"
          yes | sdkmanager --licenses

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      - name: Write local.properties
        run: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
          echo "flutter.versionCode=1" >> android/local.properties
          echo "flutter.versionName=1.0" >> android/local.properties

      - name: Flutter pub get
        run: flutter pub get

      - name: Build debug APK (verbose)
        run: flutter build apk --debug -v

      - name: Show outputs (for debugging)
        run: |
          ls -lah build/app/outputs || true
          find build -type f -name "*.apk" -print || true

      - name: Upload any APKs found
        uses: actions/upload-artifact@v4
        with:
          name: ble_bridge-apks
          path: |
            build/**/*.apk
            **/outputs/**/*.apk
